### ISSUE TITLE
Etherpad hacks

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-netsociety#3]
Override some methods (TODO: do this in awesome) to only allow the etherpad when the meeting starts and closeit when finish:
```ruby
# decidim-meetings/app/models/decidim/meetings/meeting.rb
...
      def pad_is_visible?
        return false unless pad

        (start_time - Time.current) <= 24.hours
      end

      # Overwrites method from Paddable to add custom rules in order to know
      # when a pad is writable or not.
      def pad_is_writable?
        return false unless pad_is_visible?

        (Time.current - end_time) < 72.hours
      end
...
```

**Comment by verarojman** [comment]
@microstudi will they be able to read it then? Shouldn't we allow, let's say, 2 hours after the meeting closes for the pad to be readable?

**Comment by microstudi** [comment]
Readable yes (ask pau to be sure), writable exactly as the meeting

**Comment by paarals** [comment]
hi @verarojman, the aim of this hack is that pads are enabled during the starting day/hour till the end date day/hour. 
in this project, there is a project with 4 panels. each panel has is own pad. there won't be any parallel panel, are going to be consecutive. so, during panel 1, the pad associated must be enabled during the period of this panel. each panel, will be one meeting. so we will have 4 meetings (4 panels), 1 x week, and 4 pads.

**Comment by verarojman** [comment]
@paarals Ok, I'll make them readable and writable only while meeting is open.

**Comment by microstudi** [comment]
be careful, if you make it non-readable after the meeting, no one will be able to access it!
